### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by bdlmt** [xoreaxeaxeax/sandsifter#21]
Given how long it takes to evaluate a processor, it would be great to break the search into multiple processes.

![needs-parallelization](https://user-images.githubusercontent.com/29551954/28752657-d4296c54-74f2-11e7-99c1-03089d6f804f.png)

**Comment by matepeter90** [comment]
I checked the code and actually, it is implemented how to fork multiple processes, but you have to provide the right parameters to the injector which is started by the sifter.py

Based on the example in the readme, the command which worked for me on 8 cores
`sudo ./sifter.py --unk --dis --len --sync --tick -- -P1 -t -l 1 -j 8`

`[-j jobs] ........... number of simultaneous jobs to run (default: 1)
 [-l range_bytes] .... number of base instruction bytes in each sub range (default: 0)`

When the range_bytes parameter is 0 the first thread allocates the whole search range and the others just quit, but if you set it to 1 every thread can allocate their own subrange.

**Comment by bdlmt** [comment]
Thanks for the solution. I'm still figuring out what the "number of base instruction bytes in each sub range" really means and how to optimize it, but -l4 seems to be producing good results.

**Comment by matepeter90** [comment]
It's just about breaking the search range to smaller parts for threads to work on.
Threads allocate their own part from the whole range which is 16 bytes first being all zeroes and the last is all FF-s (000000000000000000000000000000;ffffffffffffffffffffffffffffff) and try each machine code belonging to them.

I've enabled logging and printed only the first 3 bytes because the other ones (in the beginning) are just all zeroes.
Here is the part how it allocates 'subranges' for two threads with _-l 1_

```job: 0 // range: 000000;010000
job: 0 // mc:  000000
job: 2 // range: 010000;020000
job: 2 // mc:  010000
job: 2 // mc:  010001
job: 0 // mc:  000100
job: 0 // mc:  000200
job: 0 // mc:  000300
job: 0 // mc:  000400
job: 0 // mc:  000500
job: 0 // mc:  000600
job: 0 // mc:  000700
job: 0 // mc:  000800
...snip...
job: 0 // mc:  00fe00
job: 2 // mc:  0100e0
job: 0 // mc:  00ff00
job: 2 // mc:  0100e1
job: 2 // mc:  0100e2
job: 0 // range: 020000;030000
job: 2 // mc:  0100e3
job: 0 // mc:  020000
job: 2 // mc:  0100e4
job: 0 // mc:  020001
job: 2 // mc:  0100e5
job: 0 // mc:  020002
job: 2 // mc:  0100e6
```

With _-l 1_ Thread 0 allocates range: _000000;010000_ so it goes through from 000000 to _00ff00_ and requests a new 'sub range' _020000;030000_ based on the used search algorithm.

You could optimize the search algorithms or check if actually the range allocation works correctly. _move_next_range()_ and _move_next_instruction()_ are the interesting functions where this stuff is happening.
