### ISSUE TITLE
Generate basic docs from summarizer; put in wiki; crowdsource more detailed docs

### ISSUE THREAD

**Issue by corysimmons** [xoreaxeaxeax/sandsifter#51]
Maybe someone will come along and doc everything.

**Comment by rigred** [comment]
Can you elaborate a bit on this idea?
Is this about creating documentation for the instructions found by summarizer?
I have started a small project to gather test data so far and hoping to be able to work on that: https://github.com/rigred/sandsifter-tests

**Comment by corysimmons** [comment]
@rigred Yeah, interested in people crowdsourcing docs for these instructions.

**Comment by rigred** [comment]
So I can say that this idea is currently in the first planning phase. Hopefully in the coming weeks or so something will start to materialize. 

I will start a wiki with ideas and discussion for going about implementing that on my sub project (since the xoreaxeaxeax origin seems to dead with its only 1 commit) see https://github.com/rigred/sandsifter and above linked sandsifter-tests repo for that.

**Comment by corysimmons** [comment]
Thanks. Watching.
