### ISSUE TITLE
summarize.py crashes

### ISSUE THREAD

**Issue by codecnotsupported** [xoreaxeaxeax/sandsifter#66]
```
Traceback (most recent call last):
                                    File "./summarize.py", line 757, in <module>
                                                                                    gui.window.addstr(35, 1, "l: expand    L: all", gui.gray(.4))
                                                                                                                                                 _curses.error: addstr() returned ERR

```

**Comment by codecnotsupported** [comment]
dupe of #23 SOMEHOW 

> 
> @m3gat0nn4ge: For the last error, try using a slightly bigger terminal window.
> 
> Anything smaller than 97x40 will probably always lead to the same error, as the draw_infobox function currently works with fixed values:
> 
>     it draws one box from offset (37,3) with width 60 (at https://github.com/xoreaxeaxeax/sandsifter/blob/master/summarize.py#L605)
>     it writes the help strings to y-offsets 33-39 (at https://github.com/xoreaxeaxeax/sandsifter/blob/master/summarize.py#L755 and the following lines)

So just make a window with a size of some thing slightly larger than 97x40 ( terminator will tell you in the red bar )
**Still a temporary fix though, should I leave this issue open?**

**Comment by rlannon** [comment]
I ran into this issue when I used the summarizer the first time. It is sort of addressed in the README, under GUI:

> The interface assumes the terminal is of at least a certain size; if the interface is not rendering properly, try increasing the terminal size; this can often be accomplished by decreasing the terminal font size.

The display expects the terminal to be at least a certain dimension which can cause problems. The curses library will return an error if it attempts to draw outside the bounds of the terminal window, which will happen if your terminal size is too small and/or your font size is too big. Since this error isn't addressed (not in a try/except block), there is an uncaught exception which causes the crash.
